---
# This avoid breaking go when updating.
- name: Remove previous go installation
  become: true
  ansible.builtin.file:
    path: '{{ go_dir }}'
    state: absent

# Get go.
- name: Download {{ go_url }}
  ansible.builtin.get_url:
    url: '{{ go_url }}'
    dest: '{{ go_tar }}'
    mode: '0644'

# Extract
- name: Extract go.tar.gz into {{ go_dir }}
  become: true
  ansible.builtin.unarchive:
    src: '{{ go_tar }}'
    dest: /usr/local/
    mode: '0755'

- name: Remove {{ go_tar }}
  become: true
  ansible.builtin.file:
    path: '{{ go_tar }}'
    state: absent
    mode: '0755'
