# code: language=ansible
---
- name: Install php for apache2
  become: true
  ansible.builtin.apt:
    name:
      - php-common
      - php8.2-common
      - php8.2-opcache
      - php8.2-readline
      - php8.2-cli
      - libapache2-mod-php8.2
    state: latest

# php8.2-json already provided
- name: Install more php dependencies
  become: true
  ansible.builtin.apt:
    name:
      - php8.2-bcmath
      - php8.2-cli
      - php8.2-exif
      - php8.2-gd
      - php8.2-imagick
      - php8.2-mbstring
      - php8.2-pdo
      - php8.2-xml
      - php8.2-zip
      - php8.2-mysql
      - php8.2-sqlite3
      # - php8.2-pgsql
    state: latest
  notify: Restart apache2

- name: Check if exists {{ composer_path }}
  ansible.builtin.stat:
    path: '{{ composer_path }}'
  register: composer_exists

- name: Download composer-setup.php
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: '{{ install_dir }}/composer-setup.php'
    mode: '0755'
  when: not composer_exists.stat.exists

- name: Install composer
  become: true
  ansible.builtin.command:
    cmd: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    chdir: '{{ install_dir }}/'
    creates: '{{ composer_path }}'
  when: not composer_exists.stat.exists

- name: Remove {{ install_dir }}/composer-setup.php
  become: true
  ansible.builtin.file:
    path: '{{ install_dir }}/composer-setup.php'
    state: absent
  when: not composer_exists.stat.exists
