---
- name: Ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Nodesource apt key.
  become: true
  ansible.builtin.get_url:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    dest: /etc/apt/trusted.gpg.d/nodesource.asc
    mode: '0644'
    force: true
  register: add_repository_key
  ignore_errors: true

- name: Add NodeSource repositories for Node.js.
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] {{ nodejs_repo_url }} {{ ansible_distribution_release }} main"
    - "deb-src [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] {{ nodejs_repo_url }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  become: true
  ansible.builtin.apt: update_cache=yes
  when: node_repo is changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  become: true
  ansible.builtin.apt:
    name: "nodejs={{ nodejs_version | regex_replace('x', '') }}*"
    state: present
