# code: language=ansible
---
- name: Install common python dependencies & Selenium
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-poetry
      - chromium-driver
      - python3-tk
      - python3-dev
      - python3-selenium
      - python3-numpy
      - python3-mysqldb
    state: latest
