# code: language=ansible
---
# install proper terminal
- name: Install urxvt
  become: true
  ansible.builtin.apt:
    pkg: rxvt-unicode
    state: latest

- name: Correct terminal version selected
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt

- name: Set up Xdefaults
  ansible.builtin.template:
    src: 'terminal/.Xdefaults'
    dest: '{{ home_dir }}/.Xdefaults'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
