# code: language=ansible
---
- name: Install Git line tools
  become: true
  ansible.builtin.apt:
    pkg: git
    state: latest

- name: Create {{ git_config_dir }} directory if it does not exist
  ansible.builtin.file:
    path: '{{ git_config_dir }}'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Set up git config
  ansible.builtin.template:
    src: 'terminal/gitconfig'
    dest: '{{ git_config_file }}'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
