---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    pkg: zsh
    state: latest

- name: Update shell of {{ linux_user }}
  become: true
  ansible.builtin.user:
    name: '{{ linux_user }}'
    shell: /usr/bin/zsh

- name: Update shell of root
  become: true
  ansible.builtin.user:
    name: 'root'
    shell: /usr/bin/zsh

- name: Check if directory {{ oh_my_zsh_dir }} exists
  ansible.builtin.stat:
    path: '{{ oh_my_zsh_dir }}'
  register: oh_my_zsh_dir_exists

- name: Clone oh-my-zsh to {{ oh_my_zsh_dir }}
  become: true
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: '{{ oh_my_zsh_dir }}'
    depth: 1
  when: not oh_my_zsh_dir_exists.stat.exists

- name: Clone zsh-autosuggestions
  become: true
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: '{{ oh_my_zsh_dir }}/plugins/zsh-autosuggestions'
    depth: 1
  when: not oh_my_zsh_dir_exists.stat.exists

- name: Clone zsh-syntax-highlighting
  become: true
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: '{{ oh_my_zsh_dir }}/plugins/zsh-syntax-highlighting'
    depth: 1
  when: not oh_my_zsh_dir_exists.stat.exists

- name: Set up .zshrc for root
  become: true
  ansible.builtin.template:
    src: 'terminal/.zshrc.j2'
    dest: '/root/.zshrc'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Set up .zshrc for {{ linux_user }}
  ansible.builtin.template:
    src: 'terminal/.zshrc.j2'
    dest: '{{ home_dir }}/.zshrc'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
