# code: language=ansible
---
- name: Setup urxvt
  ansible.builtin.import_tasks: 0-setup-urxvt.yml

- name: Install common command line tools
  become: true
  ansible.builtin.apt:
    name:
      - make
      - btop
      - curl
      - htop
      - vim
      - vim-airline
      - wget
      - neofetch
      - rsync
    state: latest

- name: Setup git
  ansible.builtin.import_tasks: 1-setup-git.yml

- name: Setup zsh
  ansible.builtin.import_tasks: 2-setup-zsh.yml
