---
- name: Ansible Playbook to setup a new laptop
  hosts: laptop
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    linux_user: "{{ lookup('env', 'USER') }}"
  roles:
    - { role: dualboot, become: true, tags: [ 'dualboot' ] }
    - { role: terminal, become: true, tags: [ 'terminal' ] }
    - { role: python, become: true, tags: [ 'python' ] }
    - { role: fonts, become: true, tags: [ 'fonts' ] }
    - { role: code, become: true, tags: [ 'development' ] }
    - { role: images, become: true, tags: [ 'images' ] }
    - { role: browser, become: true, tags: [ 'browser' ] }
    - { role: multimedia, become: true, tags: [ 'audio', 'multimedia', 'video' ] }
    - { role: gui, become: true, tags: [ 'gui' ] }
    - { role: docker, become: true, tags: [ 'development' ] }
    - { role: keepass2, become: true, tags: [ 'security' ] }
    - { role: discord, become: true, tags: [ 'communication' ] }
    - { role: signal, become: true, tags: [ 'signal' ] }
  tasks:
    - debug: msg="You are the user {{ lookup('env','USER') }}"
