# code: language=ansible
---
- name: Install dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: Install more dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ansible-lint
    state: present

- name: Install VSCode
  ansible.builtin.import_tasks: vscode.yml

- name: Install Jetbrain
  ansible.builtin.import_tasks: jetbrain.yml
