# code: language=ansible
---
- name: Install dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: Installing Visual Studio Code
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Install more dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ansible-lint
    state: present

- name: Check if exists {{ code_user_config_dir }}
  ansible.builtin.stat:
    path: '{{ code_user_config_dir }}'
  register: code_user_config_dir_exists

- name: Create not exist {{ code_user_config_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ code_user_config_dir }}'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true
  when: not code_user_config_dir_exists.stat.exists

- name: Create not exist {{ code_user_config_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ code_user_config_dir }}'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true
  when: not code_user_config_dir_exists.stat.exists

- name: Create {{ code_user_config_dir }}/settings.json
  become: true
  ansible.builtin.template:
    src: 'code/settings.json.j2'
    dest: '{{ code_user_config_dir }}/settings.json'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
