---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Signal apt key.
  ansible.builtin.get_url:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    dest: /etc/apt/trusted.gpg.d/signal-desktop-keyring.asc
    mode: '0644'
    force: true
  register: add_repository_key
  ignore_errors: true

- name: Add Signal repository.
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/signal-desktop-keyring.asc] https://updates.signal.org/desktop/apt xenial main"
    state: present
    update_cache: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Signal
  ansible.builtin.apt:
    name: "signal-desktop"
    state: present