---
- name: Remove mariadb-server
  become: true
  ansible.builtin.apt:
    name:
      - mariadb-server
    state: absent

- name: Remove mariadb sql database
  become: true
  ansible.builtin.file:
    path: '/var/lib/mysql'
    state: absent

- name: Install mariaDB
  become: true
  ansible.builtin.apt:
    name:
      - mariadb-server
    state: latest
