---
- name: Install Apache2
  become: true
  ansible.builtin.apt:
    name:
      - apache2
    state: latest

- name: Ensure old versions of php are not installed.
  become: true
  ansible.builtin.apt:
    name:
      - libapache2-mod-php8.1
      - libapache2-mod-php8.0
    state: absent

- name: Enable the Apache2 module ssl
  become: true
  ansible.builtin.command:
    cmd: a2enmod ssl
  notify: Restart apache2

- name: Enable the Apache2 module ssl
  become: true
  ansible.builtin.command:
    cmd: a2enmod rewrite
  notify: Restart apache2

- name: Install php
  ansible.builtin.import_tasks: php.yml

- name: Install mariadb
  ansible.builtin.import_tasks: mariadb.yml
