- name: "Install mariaDB"
  become: true
  ansible.builtin.apt:
    name:
      - mariadb-server
    state: latest

- name: "Download phpMyAdmin-latest-english.tar.gz"
  ansible.builtin.get_url:
    url: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-english.tar.gz
    dest: "{{ home_dir }}/.install/phpmyadmin.tar.gz"

- name: "Create directory /var/www/html/phpmyadmin"
  ansible.builtin.file:
    path: "/var/www/html/phpmyadmin"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "755"

- name: "Extract phpmyadmin.tar.gz into /var/www/html/phpmyadmin"
  ansible.builtin.unarchive:
    src: "{{ home_dir }}/.install/phpmyadmin.tar.gz"
    dest: /var/www/html/phpmyadmin
    owner: "www-data"
    group: "www-data"
    mode: "0755"
    extra_opts: [--strip-components=1]
    creates: /var/www/html/phpmyadmin/index.php

- name: "Remove {{ home_dir }}/.install/phpmyadmin.tar.gz"
  become: true
  ansible.builtin.file:
    path: "{{ home_dir }}/.install/phpmyadmin.tar.gz"
    state: absent
