- name: "Install php for apache2"
  become: true
  ansible.builtin.apt:
    name:
      - php-common
      - php8.2-common
      - php8.2-opcache
      - php8.2-readline
      - php8.2-cli
      - libapache2-mod-php8.2
    state: latest

# php8.2-json already provided
- name: "Install more php dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - php8.2-bcmath
      - php8.2-cli
      - php8.2-exif
      - php8.2-gd
      - php8.2-imagick
      - php8.2-mbstring
      - php8.2-pdo
      - php8.2-xml
      - php8.2-zip
      - php8.2-mysql
      - php8.2-sqlite3
      # - php8.2-pgsql
    state: latest
