- name: "Install pip3"
  become: true
  ansible.builtin.apt:
    pkg: python3-pip
    state: latest

- name: "Force install pywal python package"
  become: true
  ansible.builtin.pip:
    name: pywal
    extra_args: --break-system-packages

- name: "Install compton"
  become: true
  ansible.builtin.apt:
    pkg: compton
    state: latest

- name: "Set up compton"
  ansible.builtin.copy:
    src: "templates/compton.conf"
    dest: "{{ home_dir }}/.config/compton.conf"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: install materia-gtk-theme
  become: true
  ansible.builtin.apt:
    pkg: materia-gtk-theme
    state: latest

- name: "Make sure {{ home_dir }}/Pictures/Screenshots exists"
  ansible.builtin.file:
    path: "{{ home_dir }}/Pictures/Screenshots"
    state: directory
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0755'

- name: "Install i3"
  become: true
  ansible.builtin.apt:
    pkg: i3
    state: latest

- name: "Install i3-wm"
  become: true
  ansible.builtin.apt:
    pkg: i3-wm
    state: latest

- name: "Install lock"
  become: true
  ansible.builtin.apt:
    pkg: i3lock-fancy
    state: latest

- name: "Create gtk-3.0 directory if it does not exist"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/gtk-3.0"
    state: directory
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0755'

- name: "Set up GTK3"
  ansible.builtin.template:
    src: "gtk3config"
    dest: "{{ home_dir }}/.config/gtk-3.0/settings.ini"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: "Create gtk-4.0 directory if it does not exist"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/gtk-4.0"
    state: directory
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0755'

- name: "Set up GTK4"
  ansible.builtin.template:
    src: "gtk4config"
    dest: "{{ home_dir }}/.config/gtk-4.0/settings.ini"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: "Install rofi"
  become: true
  ansible.builtin.apt:
    pkg: rofi
    state: latest

- name: "Create rofi wall directory if it does not exist"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/wal/templates"
    state: directory
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0755'

- name: "Set up rofi"
  ansible.builtin.copy:
    src: "templates/rofi.rasi"
    dest: "{{ home_dir }}/.config/wal/templates/colors-rofi-dark.rasi"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: "Install polybar"
  become: true
  ansible.builtin.apt:
    pkg: polybar
    state: latest

- name: "Install nmtui"
  become: true
  ansible.builtin.apt:
    pkg: network-manager
    state: latest

- name: "Install materia-gtk-theme"
  become: true
  ansible.builtin.apt:
    pkg: materia-gtk-theme
    state: latest

- name: "Copy i3 config"
  ansible.builtin.command: "cp -r {{ playbook_dir }}/templates/i3 {{ home_dir }}/.config/"
  args: 
      creates: "{{ home_dir }}/.config/i3"

# - name: "Fix perm i3 config"
#   ansible.builtin.file:
#     path: "{{ home_dir }}/.install/"
#     state: directory
#     owner: "{{ linux_user }}"
#     group: "{{ linux_user }}"
#     mode: '0755'

- name: "Set up permissions i3"
  ansible.builtin.file:
    dest: "{{ home_dir }}/.config"
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    recurse: yes
    mode: '0755'

- name: "Copy .local/share/icons"
  ansible.builtin.command: "cp -rv {{ playbook_dir }}/local/share/icons {{ home_dir }}/.local/share/icons"
  args: 
      creates: "{{ home_dir }}/.local/share/icons"

- name: "Copy .local/share/themes"
  ansible.builtin.command: "cp -rv {{ playbook_dir }}/local/share/themes {{ home_dir }}/.local/share/themes"
  args: 
      creates: "{{ home_dir }}/.local/share/themes"

