---
- name: Create {{ home_dir }}/Documents/Projects directory if it does not exist
  ansible.builtin.file:
    path: '{{ home_dir }}/Documents/Projects'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true

- name: Check if directory {{ home_dir }}/Documents/Projects/Lychee exists
  ansible.builtin.stat:
    path: '{{ home_dir }}/Documents/Projects/Lychee'
  register: lychee_dir

- name: Clone Lychee
  ansible.builtin.git:
    repo: https://github.com/LycheeOrg/Lychee
    dest: '{{ home_dir }}/Documents/Projects/Lychee'
  when: not lychee_dir.stat.exists
