---
- name: Set up python3-mysqldb
  become: true
  ansible.builtin.apt:
    name:
      - python3-mysqldb
    state: present

- name: Ensure Mysql is started
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create new databases named Lychee
  community.mysql.mysql_db:
    name:
      - lychee
    state: present

- name: Create database user with name 'lychee' and password 'password' with all database privileges
  community.mysql.mysql_user:
    name: lychee
    password: password
    priv: 'lychee.*:ALL'
    state: present
