---
- name: Install .env file
  ansible.builtin.template:
    src: 'lychee/.env.j2'
    dest: '{{ lychee_dir }}/.env'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Install Lychee dependencies (with dev)
  ansible.builtin.command:
    cmd: composer install
    chdir: '{{ lychee_dir }}'
    creates: '{{ lychee_dir }}/vendor'

- name: Generate security key
  ansible.builtin.command:
    cmd: php artisan key:generate
    chdir: '{{ lychee_dir }}'
