---
- name: Add {{ lychee_url }} to host file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ lychee_url }}'
    state: present
    owner: root
    group: root
    mode: '0644'

- name: Generage certificate for {{ lychee_url }}
  become: true
  ansible.builtin.command:
    cmd: ./microca -domains {{ lychee_url }}
    chdir: '{{ microca_dir }}'
    creates: '{{ lychee_cert_dir }}'
  register: lychee_test_cert

- name: Fix access of {{ lychee_cert_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ lychee_cert_dir }}'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0750'
    recurse: true
  when: lychee_test_cert is success

- name: Install lychee.test private key
  become: true
  ansible.builtin.copy:
    src: '{{ lychee_cert_dir }}/key.pem'
    dest: '/etc/ssl/private/{{ lychee_url }}.key'
    mode: '0640'
  when: lychee_test_cert is success

- name: Install {{ lychee_url }} certificate
  become: true
  ansible.builtin.copy:
    src: '{{ lychee_cert_dir }}/cert.pem'
    dest: '/etc/ssl/certs/{{ lychee_url }}.pem'
    mode: '0777'
  when: lychee_test_cert is success

- name: Add {{ lychee_url }} to conf-available
  become: true
  ansible.builtin.template:
    src: 'lychee/conf-lychee.conf.j2'
    dest: '/etc/apache2/conf-available/conf-lychee.conf'
    mode: '0644'
  when: lychee_test_cert is success
  register: lychee_conf

- name: Enable conf {{ lychee_url }}
  become: true
  ansible.builtin.command:
    cmd: a2enconf conf-lychee.conf
    creates: '/etc/apache2/conf-enabled/lychee.conf'
  when: lychee_conf is success
  notify: Restart apache2

- name: Add lychee.test to sites-available
  become: true
  ansible.builtin.template:
    src: 'lychee/lychee-test-ssl.conf.j2'
    dest: '/etc/apache2/sites-available/lychee-test-ssl.conf'
    mode: '0644'
  when: lychee_test_cert is success
  register: lychee_site

- name: Enable site lychee.test
  become: true
  ansible.builtin.command:
    cmd: a2ensite lychee-test-ssl.conf
    creates: '/etc/apache2/sites-enabled/lychee-test-ssl.conf'
  when: lychee_site is success
  notify: Restart apache2

- name: Fix access of {{ microca_root_ca }}
  ansible.builtin.file:
    path: '{{ microca_root_ca }}'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0750'

- name: Make sure the folder exists
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates
    mode: '0755'
    state: directory

- name: Setup Root CA
  become: true
  ansible.builtin.copy:
    src: '{{ microca_root_ca }}'
    dest: '/usr/local/share/ca-certificates/microca.crt'
    mode: '0755'
  register: result_import_ca

- name: Update CA Trust
  become: true
  ansible.builtin.command:
    cmd: update-ca-certificates
  when: result_import_ca is changed

- name: Install libnss3-tools
  become: true
  ansible.builtin.apt:
    pkg: libnss3-tools
    state: present

- name: Import CA into firefox & chrome
  ansible.builtin.shell: |
    ### For cert8 - Thunderbird
    for certDB in $(find {{ home_dir }}/ -name "cert8.db")
    do
        certdir=$(dirname ${certDB});
        certutil -A -n "microca root" -t "TCu,Cu,Tu" -i "{{ microca_root_ca }}" -d dbm:${certdir}
    done

    ### For cert9 (SQL - Chrome)
    for certDB in $(find {{ home_dir }}/ -name "cert9.db")
    do
        certdir=$(dirname ${certDB});
        certutil -A -n "microca root" -t "TCu,Cu,Tu" -i "{{ microca_root_ca }}" -d sql:${certdir}
    done
  args:
    executable: /usr/bin/bash

