- name: "Install pip3"
  become: true
  ansible.builtin.apt:
    pkg: python3-pip
    state: latest

- name: "Install poetry"
  become: true
  ansible.builtin.apt:
    pkg: python3-poetry
    state: latest

- name: "Install chromium-driver"
  become: true
  ansible.builtin.apt:
    pkg: chromium-driver
    state: latest

- name: "Install python3-tk"
  become: true
  ansible.builtin.apt:
    pkg: python3-tk
    state: latest

- name: "Install python3-dev"
  become: true
  ansible.builtin.apt:
    pkg: python3-dev
    state: latest

- name: "Install python3-selenium"
  become: true
  ansible.builtin.apt:
    pkg: python3-selenium
    state: latest

- name: "Install python3-numpy"
  become: true
  ansible.builtin.apt:
    pkg: python3-numpy
    state: latest
