# code: language=ansible
---
- name: Restart apache2
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Update CA Trust store
  become: true
  ansible.builtin.command:
    cmd: update-ca-certificates
