# code: language=ansible
---
- name: Install common python dependencies & Selenium
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-poetry
      - chromium-driver
      - python3-tk
      - python3-dev
      - python3-selenium
      - python3-numpy
      - python3-mysqldb
      - python3-venv
      - python3-mysqldb
      - python3-openssl
      - python3-psycopg2
      - libpq-dev
    state: latest

- name: Install ansible lint
  become: true
  ansible.builtin.apt:
    name:
      - ansible-lint
    state: latest

- name: Install ruby
  become: true
  ansible.builtin.apt:
    name:
      - ruby
      - ruby-bundler
    state: latest
