---
- name: Ensure old versions of Docker are not installed.
  become: true
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker apt key.
  become: true
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/debian/gpg'
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  register: add_repository_key

- name: Add Docker repository.
  become: true
  ansible.builtin.apt_repository:
    # repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present
    update_cache: true

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest
  notify: Restart docker

- name: Run "apt-get update"
  become: true
  ansible.builtin.apt:
    autoremove: true
    update_cache: true

- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: 'docker'
    state: present

- name: Add user "{{ linux_user }}" to the docker group
  # For the changes to take effect you need to logout, as stated here.
  # https://docs.docker.com/engine/install/linux-postinstall/
  become: true
  ansible.builtin.user:
    name: '{{ linux_user }}'
    group: 'docker'
