# code: language=ansible
---
# Install
install_dir: '{{ home_dir }}/.install'

# Projects
project_dir: '{{ home_dir }}/Documents/Projects'
sshkey_file: '{{ home_dir }}/.ssh/id_ed25519_github'

# phpMyAdmin
phpmyadmin_download_url: 'https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-english.tar.gz'
phpmyadmin_tar_gz: '{{ install_dir }}/phpmyadmin.tar.gz'
phpmyadmin_www: '/var/www/html/phpmyadmin'
phpmyadmin_url: 'phpmyadmin.dev'

# Lychee
lychee_dir: '{{ project_dir }}/Lychee'
lychee_url: 'lychee.test'
lychee_repo: 'git@github.com:LycheeOrg/Lychee'

lychee_db_name: 'lychee'
lychee_db_user: 'lychee'
lychee_db_password: 'password'

# LycheeOrg
lychee_org_dir: '{{ project_dir }}/LycheeOrg'
lychee_org_url: 'lycheeorg.test'
lychee_org_repo: 'git@github.com:LycheeOrg/LycheeOrg.github.io'

# Microca
microca_dir: '{{ install_dir }}/microca'
microca_root_ca: '{{ microca_dir }}/microca.pem'
