# code: language=ansible
---
- name: Check if exists {{ lychee_dir }}
  ansible.builtin.stat:
    path: '{{ lychee_dir }}'
  register: lychee_dir_exists

- name: Clone Lychee
  ansible.builtin.git:
    repo: '{{ lychee_repo }}'
    dest: '{{ lychee_dir }}'
    key_file: "{{ sshkey_file }}"
  when: not lychee_dir_exists.stat.exists

- name: Ensure Mysql is started
  become: true
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create new databases named {{ lychee_db_name }}
  become: true
  community.mysql.mysql_db:
    name:
      - '{{ lychee_db_name }}'
    state: present

- name: Create database user for {{ lychee_db_name }} with all database privileges
  become: true
  community.mysql.mysql_user:
    name: '{{ lychee_db_user }}'
    password: '{{ lychee_db_password }}'
    priv: '{{ lychee_db_name }}.*:ALL'
    state: present

- name: Install .env file
  ansible.builtin.template:
    src: 'lychee/.env.j2'
    dest: '{{ lychee_dir }}/.env'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Install Lychee dependencies (with dev)
  ansible.builtin.command:
    cmd: composer install
    chdir: '{{ lychee_dir }}'
    creates: '{{ lychee_dir }}/vendor'

- name: Generate security key
  ansible.builtin.command:
    cmd: php artisan key:generate
    chdir: '{{ lychee_dir }}'

- name: Migrate database
  ansible.builtin.command:
    cmd: php artisan migrate
    chdir: '{{ lychee_dir }}'

- name: Update owner & permissions of {{ lychee_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ lychee_dir }}'
    owner: '{{ linux_user }}'
    group: 'www-data'
    recurse: true
  tags: ['skip_ansible_lint']

- name: Setup {{ lychee_url }}
  ansible.builtin.import_tasks: 'install-site.yml'
  vars:
    site_url: '{{ lychee_url }}'
    site_root_dir: '{{ lychee_dir }}'
    site_public_dir: '{{ lychee_dir }}/public'
    site_dir_conf: '{{ site_url }}-dir.conf'
    site_ssl_conf: '{{ site_url }}-ssl.conf'
