# code: language=ansible
---
- name: Check if exists {{ lychee_org_dir }}
  ansible.builtin.stat:
    path: '{{ lychee_org_dir }}'
  register: lychee_org_dir_exists

- name: Clone LycheeOrg.github.io
  ansible.builtin.git:
    repo: '{{ lychee_org_repo }}'
    dest: '{{ lychee_org_dir }}'
    key_file: '{{ sshkey_file }}'
  when: not lychee_org_dir_exists.stat.exists

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-git
      - python3-pytest
      - python3-markdown
    state: latest

- name: Compile
  community.general.make:
    chdir: '{{ lychee_org_dir }}'

- name: Setup {{ lychee_org_url }}
  ansible.builtin.import_tasks: 'install-site.yml'
  vars:
    site_url: '{{ lychee_org_url }}'
    site_root_dir: '{{ lychee_org_dir }}/dist/'
    site_public_dir: '{{ lychee_org_dir }}/dist/'
    site_dir_conf: '{{ site_url }}-dir.conf'
    site_ssl_conf: '{{ site_url }}-ssl.conf'
