---
- name: Set up python3-mysqldb
  become: true
  ansible.builtin.apt:
    name:
      - python3-mysqldb
    state: present

- name: Ensure Mysql is started
  become: true
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create new databases named {{ lychee_db_name }}
  become: true
  community.mysql.mysql_db:
    name:
      - '{{ lychee_db_name }}'
    state: present

- name: Create database user for {{ lychee_db_name }} with all database privileges
  become: true
  community.mysql.mysql_user:
    name: '{{ lychee_db_user }}'
    password: '{{ lychee_db_password }}'
    priv: '{{ lychee_db_name }}.*:ALL'
    state: present
