- name: "Create .install directory if it does not exist"
  ansible.builtin.file:
    path: "{{ home_dir }}/.install/"
    state: directory
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: '0755'
    recurse: true

- name: "Ensure Fonts are installed."
  become: true
  ansible.builtin.apt:
    name:
      - fonts-dejavu
      - fonts-jetbrains-mono
      - fonts-noto
      - fonts-cantarell
    state: latest

- name: "Check if directory /usr/local/share/fonts/NerdFonts exists"
  ansible.builtin.stat:
    path: "/usr/local/share/fonts/NerdFonts"
  register: nerd_fonts_dir

- name: "Clone Nerd Fonts repo to {{ home_dir }}/.install/nerd-fonts"
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: "{{ home_dir }}/.install/nerd-fonts"
    update: no
  when: not nerd_fonts_dir.stat.exists

- name: "Execute font installation" 
  become: true
  shell:
    cmd: "bash install.sh -S"
    chdir: "{{ home_dir }}/.install/nerd-fonts/"
  when: not nerd_fonts_dir.stat.exists

# Only rebuild cache if we actually insalled the Nerd Fonts
- name: "Rebuild font cache"
  become_user: "{{ linux_user }}"
  ansible.builtin.command: "fc-cache -fv"
  when: not nerd_fonts_dir.stat.exists
