# code: language=ansible
---
- name: Create not exist {{ install_dir }}
  ansible.builtin.file:
    path: '{{ install_dir }}/'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true

- name: Ensure Fonts are installed
  become: true
  ansible.builtin.apt:
    name:
      - fonts-dejavu
      - fonts-jetbrains-mono
      - fonts-noto
      - fonts-cantarell
    state: latest

- name: Check if exists {{ nerd_font_install_dir }}
  ansible.builtin.stat:
    path: '{{ nerd_font_install_dir }}'
  register: nerd_fonts_exists

- name: Clone Nerd Fonts repo to {{ nerd_font_git_dir }}
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: '{{ nerd_font_git_dir }}'
    update: false
  when: not nerd_fonts_exists.stat.exists
  register: clone_nerd_fonts

- name: Execute font installation
  become: true
  ansible.builtin.command:
    cmd: "bash install.sh -S"
    chdir: '{{ nerd_font_git_dir }}/'
  when: clone_nerd_fonts is success
  register: install_fonts

# Only rebuild cache if we actually installed the Nerd Fonts
- name: Rebuild font cache
  become_user: '{{ linux_user }}'
  ansible.builtin.command: fc-cache -fv
  when: install_fonts is success

- name: Update permissions of {{ home_dir_local }}
  become: true
  ansible.builtin.file:
    path: '{{ home_dir_local }}'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true
  when: install_fonts is success
