---
# Install
install_dir: '{{ home_dir }}/.install'

composer_path: '/usr/local/bin/composer'

# Set the version of Node.js to install ("12.x", "13.x", "14.x", "15.x", etc.).
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "20.x"
nodejs_repo_url: 'https://deb.nodesource.com/node_{{ nodejs_version }}'
