---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed.
  apt:
    name: gnupg2
    state: present

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    # repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
  # notify: restart docker
  ignore_errors: true

- name: Run "apt-get update"
  ansible.builtin.apt:
    autoremove: true
    update_cache: true

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user "{{ linux_user }}" to the docker group
  # For the changes to take effect you need to logout, as stated here.
  # https://docs.docker.com/engine/install/linux-postinstall/
  ansible.builtin.user:
    name: "{{ linux_user }}"
    group: docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
