# code: language=ansible
---
- name: Check if exists {{ install_dir }}
  ansible.builtin.stat:
    path: '{{ install_dir }}'
  register: install_dir_exists

- name: Create not exist {{ install_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ install_dir }}/'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
    recurse: true
  when: not install_dir_exists.stat.exists

- name: Check if exists {{ i3lock_fancy_rapid_install_location }}
  ansible.builtin.stat:
    path: '{{ i3lock_fancy_rapid_install_location }}'
  register: i3lock_fancy_rapid_exists

# Rather than using i3lock-fancy which is rather slow in the bluring process, we use this version
- name: Clone i3lock-fancy-rapid to {{ i3lock_fancy_rapid_dir }}
  ansible.builtin.git:
    repo: https://github.com/yvbbrjdr/i3lock-fancy-rapid
    dest: '{{ i3lock_fancy_rapid_dir }}'
    depth: 1
  when: not i3lock_fancy_rapid_exists.stat.exists
  register: i3lock_fancy_rapid_clone

# Required dependency to compile
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - libx11-dev
      - i3lock
      - scrot
      - imagemagick
    state: latest

# Compilation step
- name: Compile i3lock-fancy-rapid
  community.general.make:
    chdir: '{{ i3lock_fancy_rapid_dir }}'
  when: i3lock_fancy_rapid_clone is success and not i3lock_fancy_rapid_clone is skipped
  register: i3lock_fancy_rapid_compile

# Install executable
- name: Install i3lock-fancy-rapid
  become: true
  ansible.builtin.copy:
    src: '{{ i3lock_fancy_rapid_dir }}/i3lock-fancy-rapid'
    dest: '{{ i3lock_fancy_rapid_install_location }}'
    mode: '0755'
  when: i3lock_fancy_rapid_compile is success and not i3lock_fancy_rapid_compile is skipped

- name: Remove {{ i3lock_fancy_rapid_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ i3lock_fancy_rapid_dir }}'
    state: absent
  when: i3lock_fancy_rapid_compile is success and not i3lock_fancy_rapid_compile is skipped
