---
- name: Install materia-gtk-theme
  become: true
  ansible.builtin.apt:
    pkg: materia-gtk-theme
    state: latest

- name: Create gtk-3.0 directory if it does not exist
  ansible.builtin.file:
    path: '{{ config_dir }}/gtk-3.0'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Set up GTK3
  ansible.builtin.template:
    src: 'gui/gtk3config'
    dest: '{{ config_dir }}/gtk-3.0/settings.ini'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Create gtk-4.0 directory if it does not exist
  ansible.builtin.file:
    path: '{{ config_dir }}/gtk-4.0'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Set up GTK4
  ansible.builtin.template:
    src: 'gui/gtk4config'
    dest: '{{ config_dir }}/gtk-4.0/settings.ini'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'
