---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
      - rofi
      - polybar
      - network-manager
      - compton
      - xautolock
      - feh
    state: latest

- name: Force install pywal python package
  become: true
  ansible.builtin.pip:
    name: pywal
    extra_args: --break-system-packages

- name: Set up compton
  ansible.builtin.copy:
    src: 'templates/gui/compton.conf'
    dest: '{{ config_dir }}/compton.conf'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Make sure {{ home_dir }}/Pictures/Screenshots exists
  ansible.builtin.file:
    path: '{{ home_dir }}/Pictures/Screenshots'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Install i3lock-fancy-rapid
  ansible.builtin.import_tasks: install-i3lock-fancy-rapid.yml

- name: Install i3
  become: true
  ansible.builtin.apt:
    name:
      - i3
      - i3-wm
    state: latest

- name: Install GTK dependencies
  ansible.builtin.import_tasks: install-gtk-stuff.yml

- name: Create rofi wall directory if it does not exist
  ansible.builtin.file:
    path: '{{ config_dir }}/wal/templates'
    state: directory
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'

- name: Set up rofi
  ansible.builtin.copy:
    src: 'templates/gui/rofi.rasi'
    dest: '{{ config_dir }}/wal/templates/colors-rofi-dark.rasi'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    mode: '0755'


- name: Copy i3 config
  ansible.builtin.command: cp -r {{ playbook_dir }}/templates/gui/i3 {{ config_dir }}/
  args:
    creates: '{{ config_dir }}/i3'

- name: Set up permissions i3
  become: true
  ansible.builtin.file:
    dest: '{{ config_dir }}'
    owner: '{{ linux_user }}'
    group: '{{ linux_user }}'
    recurse: true
    mode: '0755'

- name: Copy .local/share/icons
  ansible.builtin.command: cp -rv {{ playbook_dir }}/local/share/icons {{ home_dir }}/.local/share/icons
  args:
    creates: '{{ home_dir }}/.local/share/icons'

- name: Copy .local/share/themes
  ansible.builtin.command: cp -rv {{ playbook_dir }}/local/share/themes {{ home_dir }}/.local/share/themes
  args:
    creates: '{{ home_dir }}/.local/share/themes'
