# code: language=ansible
---
- name: Purge useless firmware
  become: true
  ansible.builtin.apt:
    pkg: raspi-firmware
    state: absent
    purge: true

- name: Update the /etc/default/grub file
  become: true
  ansible.builtin.lineinfile:
    path: '/etc/default/grub'
    regexp: '#GRUB_DISABLE_OS_PROBER=false'
    line: 'GRUB_DISABLE_OS_PROBER=false'
    state: present
    backup: true
  notify: Update grub

- name: Install ntp
  become: true
  ansible.builtin.apt:
    pkg: ntp
    state: latest
